# Native `terraform test`. Uses a mocked AWS provider so no real credentials or
# resources are needed — validates the client's secure-by-default behaviour.

mock_provider "aws" {}

run "secure_defaults" {
  command = plan

  variables {
    config = {
      name         = "test-client"
      user_pool_id = "eu-central-1_TESTPOOL0"
    }
  }

  assert {
    condition     = aws_cognito_user_pool_client.this.generate_secret == true
    error_message = "A confidential client secret must be generated by default."
  }

  assert {
    condition     = !contains(aws_cognito_user_pool_client.this.allowed_oauth_flows, "implicit")
    error_message = "The implicit OAuth flow must never be allowed (PCI DSS Req 8)."
  }

  assert {
    condition     = contains(aws_cognito_user_pool_client.this.allowed_oauth_flows, "code")
    error_message = "The authorization-code OAuth flow must be allowed by default."
  }

  assert {
    condition     = !contains(aws_cognito_user_pool_client.this.explicit_auth_flows, "ALLOW_USER_PASSWORD_AUTH")
    error_message = "The password-based auth flow must be excluded by default (PCI DSS Req 8)."
  }

  assert {
    condition     = contains(aws_cognito_user_pool_client.this.explicit_auth_flows, "ALLOW_USER_SRP_AUTH")
    error_message = "SRP auth flow must be enabled by default."
  }

  assert {
    condition     = aws_cognito_user_pool_client.this.prevent_user_existence_errors == "ENABLED"
    error_message = "prevent_user_existence_errors must default to ENABLED (PCI DSS Req 8)."
  }

  assert {
    condition     = aws_cognito_user_pool_client.this.enable_token_revocation == true
    error_message = "Token revocation must be enabled by default."
  }

  assert {
    condition     = aws_cognito_user_pool_client.this.access_token_validity == 60
    error_message = "Access token validity must default to 60 minutes."
  }

  assert {
    condition     = aws_cognito_user_pool_client.this.refresh_token_validity == 30
    error_message = "Refresh token validity must default to 30 days."
  }
}

run "implicit_flow_is_rejected" {
  command = plan

  variables {
    config = {
      name                = "test-client"
      user_pool_id        = "eu-central-1_TESTPOOL0"
      allowed_oauth_flows = ["code", "implicit"]
    }
  }

  # No escape hatch for the implicit flow — rejected by config validation.
  expect_failures = [
    var.config,
  ]
}

run "password_auth_is_blocked_without_escape_hatch" {
  command = plan

  variables {
    config = {
      name                = "test-client"
      user_pool_id        = "eu-central-1_TESTPOOL0"
      explicit_auth_flows = ["ALLOW_REFRESH_TOKEN_AUTH", "ALLOW_USER_PASSWORD_AUTH"]
      # allow_password_auth intentionally left at its false default
    }
  }

  expect_failures = [
    aws_cognito_user_pool_client.this,
  ]
}

run "password_auth_allowed_with_escape_hatch" {
  command = plan

  variables {
    config = {
      name                = "test-client"
      user_pool_id        = "eu-central-1_TESTPOOL0"
      explicit_auth_flows = ["ALLOW_REFRESH_TOKEN_AUTH", "ALLOW_USER_PASSWORD_AUTH"]
      allow_password_auth = true
    }
  }

  assert {
    condition     = contains(aws_cognito_user_pool_client.this.explicit_auth_flows, "ALLOW_USER_PASSWORD_AUTH")
    error_message = "Escape hatch must permit ALLOW_USER_PASSWORD_AUTH."
  }
}
